-- Generated by nwg-displays on 2026-05-31 at 17:51:05. Do not edit manually.
-- Ported to Lua (Hyprland 0.55+). Original: monitors.conf

hl.monitor({
  output = "eDP-1",
  mode = "1366x768@60.02",
  position = "0x0",
  scale = 1.0,
})
