-- Generated by nwg-displays on 2026-02-03 at 18:12:49. Do not edit manually.
-- Ported to Lua (Hyprland 0.55+). Original: workspaces.conf
-- workspace=1,monitor:eDP-1,default:true
-- workspace=2,monitor:HDMI-A-1,default:true

hl.workspace_rule({
  workspace = "1",
  monitor = "eDP-1",
  default = true,
})

hl.workspace_rule({
  workspace = "2",
  monitor = "HDMI-A-1",
  default = true,
})
