# Configurações de Monitoramento Avançado
fps
frame_timing=1

# Hardware (Uso, Temperatura e Watts)
gpu_stats
gpu_temp
gpu_power

cpu_stats
cpu_temp
cpu_power

# Memória
ram
vram

# Posição e Estilo
position=top-left
table_columns=3
background_alpha=0.5
